language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak64-trunk
  - Squeak64-5.3
  - Squeak64-5.2
  - Squeak32-5.3
  - Squeak32-5.2
  - Squeak32-5.1
  - Squeak32-5.0
  - Squeak32-4.6
  
os:
  - linux
  - osx

matrix:
    allow_failures:
        - smalltalk: Squeak-trunk
        - smalltalk: Squeak64-trunk
